# Generated by Django 5.2.9 on 2026-01-03 17:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('settled_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-settled_date'],
            },
        ),
        migrations.AddField(
            model_name='debt',
            name='amount_settled',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='debt',
            name='person_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='debt',
            name='type',
            field=models.CharField(choices=[('BORROWED', 'Borrowed'), ('GIVEN', 'Given')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['user', 'status'], name='debts_debt_user_id_637101_idx'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='debts.debt'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['debt', 'settled_date'], name='debts_settl_debt_id_84123e_idx'),
        ),
    ]
