# Generated by Django 5.2.9 on 2026-01-04 12:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['installment_number']},
        ),
        migrations.RemoveField(
            model_name='emi',
            name='monthly_amount',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='total_months',
        ),
        migrations.AddField(
            model_name='emi',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emi',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='emi',
            name='total_installments',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installment',
            name='installment_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('emi', 'installment_number')},
        ),
    ]
